# it will map IAM user with kubernetes
# Give the command as "kubectl get configmap aws-auth -n kube-system -o yaml"
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::695862934667:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-cZKxVMVXh27o
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  # search in google as "edit aws auth configmap" --> click on "Amazon AWS Documentation" --> click on "edit configmap manually"(above "Edit Configmap with Eksctl")
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::695862934667:user/vinod
      username: vinod
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-09T05:26:39Z"
  name: aws-auth
  namespace: kube-system
  uid:  b07bf4a2-4838-4d61-805a-74c2a7418433 # This will change everytime when we delete the kubernetes cluster, either you don't give it or change it every time with new uid of kubernetes cluster.
  #To get new uid of kubernetes cluster --> kubectl get configmap aws-auth -n kube-system -o yaml
