apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::695862934667:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-YF3PfqHUihMr
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-08T05:35:58Z"
  name: aws-auth
  namespace: kube-system
  uid: 5d04cb5a-c397-4474-836a-daea5d8fa555
